pipeline:
  drone-compose-volume:
    image: docker/compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    secrets: [mysql_root_password, mysql_database, mysql_user, mysql_password]
    commands:
      - cd compose_volume
      - mkdir -p /tmp/docker_compose_volume
      - cp ./sakila-schema.sql /tmp/docker_compose_volume
      - docker-compose stop
      - docker-compose rm -f
      - docker-compose up -d
