version: "3.0"
services:
  mysql:
    container_name: drone_mysql
    command: --default-authentication-plugin=mysql_native_password --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /tmp/docker_compose_volume/sakila-schema.sql:/docker-entrypoint-initdb.d/sakila-schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: drone_demo
      MYSQL_USER: drone
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
